apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-js-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-js-app
  template:
    metadata:
      labels:
        app: my-js-app
    spec:
      containers:
        - name: my-js-app
          image: <your_ecr_image>
          ports:
            - containerPort: 3000
